const alunos = [
  { nome: "Alexandre de Lima Junior", pasta: "alexandre-junior" },
  { nome: "Alexandre Henrique Pereira de Araujo", pasta: "alexandre-araujo" },
  { nome: "Andrey Canalli Rodrigues", pasta: "andrey-rodrigues" },
  { nome: "Breno Santos de Oliveira", pasta: "breno-oliveira" },
  { nome: "Cleiton Candido da Silva Junior", pasta: "cleiton-junior" },
  { nome: "Danilo Gomes Silva", pasta: "danilo-gomes" },
  { nome: "Danilo Gonçalves da Silva", pasta: "danilo-goncalves" },
  { nome: "Davi Moreira", pasta: "davi-moreira" },
  { nome: "Davy Santos Gama", pasta: "davy-gama" },
  { nome: "Eduardo Dias Roxo da Silva", pasta: "eduardo-roxo" },
  { nome: "Geovana Reis de Souza", pasta: "geovana-souza" },
  { nome: "Giovanna Ramos Valério", pasta: "giovanna-valerio" },
  { nome: "Giovanni Sacco Prando", pasta: "giovanni-prando" },
  { nome: "Guilherme Miranda Murillo", pasta: "guilherme-murillo" },
  { nome: "Guilherme Santos Araujo", pasta: "guilherme-araujo" },
  { nome: "Gustavo Oliveira Almeida", pasta: "gustavo-almeida" },
  { nome: "Gustavo Viveiros de Brito", pasta: "gustavo-brito" },
  { nome: "Higor Torres Barbosa Cigo", pasta: "higor-cigo" },
  { nome: "Igor Bergas Rodrigues da Costa", pasta: "igor-costa" },
  { nome: "Italo Pereira Gomes", pasta: "italo-gomes" },
  { nome: "João Victhor Santos de Oliveira", pasta: "joao-victhor" },
  { nome: "Lara Pecellin Sato", pasta: "lara-sato" },
  { nome: "Leonardo Ferreira de Paiva", pasta: "leonardo-paiva" },
  { nome: "Lucas Favalli Barbosa da Silva", pasta: "lucas-favalli" },
  { nome: "Luiza Cabral Crepaldi", pasta: "luiza-crepaldi" },
  { nome: "Maria Eduarda Bucci Costa", pasta: "maria-bucci" },
  { nome: "Nicolas da Silva Mira", pasta: "nicolas-mira" },
  { nome: "Pedro Otavio Martins Laube", pasta: "pedro-laube" },
  { nome: "Rafael Rodrigues Pimentel", pasta: "rafael-pimentel" },
  { nome: "Renan Alves Ferreira Silva", pasta: "renan-ferreira" },
  { nome: "Rui Kojima Bastos", pasta: "rui-bastos" },
  { nome: "Thaís Poma da Silva", pasta: "thais-silva" }
];